Add How to get started with X a guide for TensorFlow.js Users.md
NoobTW/tfjs-tutorials pull request #11
Opened 2019-01-12 13:21 UTC by aver803bath5

* Haven't add link in the Readme.md.
* Translate [this page](https://js.tensorflow.org/tutorials/how-to-get-started.html) into Traditional Chinese.

2019-01-12 13:22 UTC, aver803bath5 commented
I have a comment in the line 74. Please read it before you merge.

2019-01-12 14:30 UTC, NoobTW requested changes
Nice PR; thanks for it.

I've added some review, please read it and make some commits or comments.

2019-01-12 14:30 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +使用 TensorFlow.js 做機器學習需要許多不同領域的知識，特別是：機器學習以及人經網路、JavaScript含有 Node.JS 或是基於瀏覽器相關的開發知識，依照您的背景，您可能不會熟悉其中一個或是以上的領域，在網路上有相當多很好的學習機緣，而我們也希望這份指南能夠成為您補中這些領域知識起點。
幾個建議：
- 機器學習與**神**~~人~~經網路
- JavaScript 前後間加空白（[reference](https://github.com/sparanoid/chinese-copywriting-guidelines#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%96%93%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)）
- 您可能**會不**~~不會~~熟悉
- 學習**資源**~~機緣~~
- **補充**~~補中~~知識起點

2019-01-12 14:30 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +## How to get started with **Machine Learning**
建議可以翻成「如何開始機器學習」

2019-01-12 14:30 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +有一個能夠起頭的關於神經網路的高水平介紹是 3blue1brown（一個 Youtube 頻道） 所提供的 Neural Networks 的教學影片（有中文字幕）。
有一個能夠起頭的關於神經網路的高**水準**~~水平~~介紹是 3blue1brown ~~（一個 Youtube 頻道）~~ 所提供的**神經網路** ~~Neural Networks 的~~ 教學 ~~影片（有中文字幕）~~。

2019-01-12 14:30 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +機器學習是一門很重數學的學科，然而，如果您史是單單使用機器學習的模型的話，不需要去了解數學，但是如果您打算修改機器學習的模型或是從零到有建立一個新的模型的話，熟悉下面的數學概念將會很有幫助。
- 您**只**~~史~~是單單使用機器學習

2019-01-12 14:30 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +語言的大概了解或是教學的話，這些資源是一個很好的開始。
多餘換行

2019-01-12 14:30 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +* [*給恐龍的現代 JavaScript 解釋（Modern JavaScript Explained For Dinosaurs）](https://medium.com/the-node-js-collection/modern-javascript-explained-for-dinosaurs-f695e9747b70) by Peter Jang：這篇文章介紹一些現在 Web 開發工
直接修正為正確的標題好了。註解可以移除。

2019-01-12 14:30 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +### 創建學習資源以及部落格貼文
**建立**~~創建~~

2019-01-12 14:54 UTC, aver803bath5 commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +語言的大概了解或是教學的話，這些資源是一個很好的開始。
不好意思，我沒有檢查到多餘換行，請問在第幾行呢？

2019-01-12 14:55 UTC, aver803bath5 commented
I make some changes base on your suggestions. Would you please review again? Thank you.

2019-01-12 15:04 UTC, NoobTW requested changes

2019-01-12 15:04 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +有一個能夠起頭的關於神經網路的高水平介紹是 3blue1brown 所提供的 Neural Networks 的教學。
- 所提供的 Neural Networks ~~的~~教學
- 「水平」比較好還是「水準」比較好？

2019-01-12 15:04 UTC, NoobTW commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +* [*給恐龍的現代 JavaScript 解釋（Modern JavaScript Explained For Dinosaurs）](https://medium.com/the-node-js-collection/modern-javascript-explained-for-dinosaurs-f695e9747b70) by Peter Jang：這篇文章介紹一些現在 Web 開發工
多一個 `*`？

2019-01-13 03:43 UTC, aver803bath5 commented on tutorials/How to get started with X a guide for TensorFlow.js Users.md
> +有一個能夠起頭的關於神經網路的高水平介紹是 3blue1brown 所提供的 Neural Networks 的教學。
水準好了，水平感覺像是對岸的翻譯XD

2019-01-13 06:51 UTC, NoobTW approved these changes

2019-01-13 06:51 UTC, merged